flags: {}
extra-package-dbs: []
packages:
- '.'
- location:
    git: https://github.com/iu-parfunc/lvars.git
    commit: 51df52ec577d825deb1c8f642553350890a4041a
  subdirs:
  - src/par-classes
  - src/par-collections
#  - src/lvish
  - deps/concurrent-skiplist
  - deps/ctrie
docker:
  image: liquidhaskell
  enable: false
allow-newer: true
extra-deps:
- chaselev-deque-0.5.0.5
- ctrie-0.1.0.3
- pcg-random-0.1.3.4
- thread-local-storage-0.1.0.4
- tslogger-0.2.1.0
compiler-check: newer-minor
resolver: lts-8.9
